name: Dynamodb setup demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [pull_request]
jobs:
  Dynamodb-setup-actions:
    runs-on: ubuntu-20.04
    container: node:16
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8002:8000
    steps:
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          /tmp/aws/install --update
          rm -rf /tmp/aws/
          aws --version
      - name: Setup DynamoDB Local
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-northeast-1
        uses: actions/checkout@v3
        run: |
          aws dynamodb list-tables --endpoint-url http://localhost:8002
          aws dynamodb list-tables --endpoint-url http://localhost:8000
          aws dynamodb list-tables --endpoint-url http://dynamodb:8002
          aws dynamodb list-tables --endpoint-url http://dynamodb:8000
          echo "finish"
